networks:
  backend:
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Senha@123
    networks:
      - backend
    ports:
      - "1433:1433"

  smartvet:
    build:
      context: .
      dockerfile: SmartVet/SmartVet.WebAPI/Dockerfile
    networks:
      - backend
    ports:
      - "8080:8080"
      # - "8081:8081"
    depends_on:
      - sqlserver
    environment:
      PostgreSql: ${PostgreSql}
